# Generated by Django 3.2.12 on 2022-04-08 13:17

import crm.helpers.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Meeting', 'Meeting'), ('Call', 'Call')], max_length=7)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('task_state', models.CharField(choices=[('completed', 'completed'), ('in progress', 'in progress'), ('not started', 'not started')], max_length=11)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('offer_date', models.DateField(auto_now_add=True)),
                ('offer_validity', models.DateField()),
                ('offered_quantity', models.DateField(max_length=6)),
                ('offer_price', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(4), crm.helpers.validators.only_digits_validator])),
                ('offer_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('eic', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(9), crm.helpers.validators.only_digits_validator])),
                ('representative_first_name', models.CharField(max_length=30, validators=[crm.helpers.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('representative_last_name', models.CharField(max_length=30, validators=[crm.helpers.validators.only_letters_validator, django.core.validators.MinLengthValidator(2)])),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(auto_created=True)),
                ('customer', models.CharField(max_length=100)),
                ('eic', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(9), crm.helpers.validators.only_digits_validator])),
                ('annual_consumption', models.CharField(max_length=6)),
                ('price', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('contract_expiration', models.DateField()),
                ('contract_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
