# Generated by Django 3.2.12 on 2022-04-21 14:45

import crm.helpers.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='eic',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(9), crm.helpers.validators.only_digits_validator]),
        ),
    ]
