# Generated by Django 3.2.12 on 2022-04-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220421_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customers'),
        ),
    ]
