# Generated by Django 3.2.12 on 2022-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_contracts_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='contracts',
            name='contract_date',
            field=models.DateField(),
        ),
    ]
