# Generated by Django 3.2.12 on 2022-04-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20220423_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offered_quantity',
            field=models.CharField(max_length=6),
        ),
    ]
