# Generated by Django 3.2.12 on 2022-04-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_offers_offered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.customers'),
            preserve_default=False,
        ),
    ]
