# Generated by Django 3.2.12 on 2022-04-08 17:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='crmuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='crmuser',
            name='last_name',
        ),
    ]
